language: node_js
node_js:
- node

script:
- yarn build

cache: yarn

deploy:
  skip_cleanup: true
  provider: pages
  local-dir: build
  github-token:
    secure: "X8wI+PiIYkMk4YCZnrpMZ1Xd3AzE7QAPnBLfGYt12NuG+pSSftqyBaWEvkmG0BueREypZCbphugaeNG7V+DvMySkXGqbQvl0JiDii0b6fFTzrW4yfzBW76/uzmDeGFnvpfu5abXBdk0uXeLnmTcuAdkl5nYMfEjvAO8uaT1Trig+N1X8LvmvrCWDE4hsFMI/0rCC6qGlqqpiAZ/qpqnNQSaKsVJhNTSoWaXueUy97yl8pimkZmeisBbbvEPt4c0kLMmySb9U+iF+ThLDk6ChxOQ3rsEoc45Sbzo3IjoODy0bbf0cMe/Q3vbYbooamzYqAbCof/Xw/j+nDiUzM8N6M2QyUIyBrIL7KC0hoTrnDAv+LjE+ViJenMTPFf5QMSNVkz2mZJFc4Y0FcDWKhu3o4+ZdikOixUf/+nHN0H+OlmyY6hbYK9zg5FiC3Oa3vGFE57fOV4kgQ3KjijLX/EjJK7LbsP+M+dFPFsu15laPrDabF1BgB8kZGhNu9AreR07uPcrvvtQw5c9XhT4Ps5TThyqjH7dQ7XPhpY6HWzo+ILVvKIEbV9GhWKqni6ZylayS78fyQah+y15XDbW5zYQdU6DaVKIF73vEwUze91i+racaZ/Tp7GNI9D2/aFDS1eCV2xqXvrywzhv+AIunhHkHHRqo5PNDHXmcFttVAiBEkJk="